version: "3"

services:

  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - TEST_ENV=CI
      - TEST_PORT=8080
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

volumes:
  yarn:
